name: PHPUnit
on: push
jobs:
  phpspec:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: php-actions/composer@v5
        with:
          args: --prefer-dist
          php_version: 8.0
      - name: PHPUnit
        run: bin/phpunit tests/
